### ISSUE TITLE
Remove importer, describe init.go in README

### ISSUE THREAD

**Issue by 9len** [trinchan/slackbot#10]
This is maybe more of a question rather than an issue:

Why not just check in init.go, and remove the importer.sh/go stuff entirely? Either way the end user has to modify a list of things, the only difference i see is the requirement of including the "_" prefix. Since the end user is probably just copy/pasting your examples, it might be nice to save them the `go generate` round-trip.

Just a thought.

Thanks for a great framework!

**Comment by trinchan** [comment]
Hey, thanks for your question.

The idea was that if I forced users to update `init.go`, when you wanted to update to the latest version of the framework, update would complain of a dirty working tree. But I ended up including the shell script anyway in the repo... that was a mistake. The idea was that people would make their own (open source?) robots _outside_ the slackbot/robots directory with bots that implement the bot interface because bots don't necessarily have to be in the `robots` directory. Then, by only changing the shell script to point to the various robots, you could generate the importer for your setup. I should probably take out the shell script and move it to the readme so we can properly update the framework using `go get -u`.

**Comment by 9len** [comment]
Yeah I think adding something to the README that says "Hey, put an init.go file in this location with these contents" is probably fine. If you leave it in .gitignore you still solve the dirty tree problem.

FWIW, we're using it for four different bots, each answering different slash commands, from the same runtime, and it's great. thanks again!

**Comment by 9len** [comment]
In lieu of this, I submitted a PR that makes it possible to use slackbot without using slackbot's `main` function: https://github.com/trinchan/slackbot/pull/19. This lets folks use their own main function easily, and obviates the need for init.go (which I left alone, and which still works fine)

**Comment by 9len** [comment]
#19 addresses my use-case; I still think checking in `init.go` and documenting necessary changes is probably the right way to go, since `importer.sh` makes the tree dirty anyway, but use of slackbot as a library covers our needs. Thanks!
